name: Lede-CI
on: workflow_dispatch

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      NOW: ${{ steps.prepare.outputs.NOW }}
    steps:
      - name: Prepare
        id: prepare
        run: echo "NOW=$(date +'%Y%m%d%H:%M:%S')" >> $GITHUB_OUTPUT
  build:
    name: ${{ matrix.NOW }}
    runs-on: ubuntu-latest
    needs: [prepare]
    strategy:
      matrix:
        NOW: ${{ needs.prepare.outputs.NOW }}
    steps:
      - name: Setup
        run: |
          echo "${{ toJSON(github) }}"
      
      - name: Checkout
        run: |
          echo "checkout"
