name: "Build CI for Lede firmware"
run-name: "Building Lede firmware #${{ github.run-number }}"

on: workflow_dispatch

jobs:
  build:
    name: Building Lede firmware
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          echo "${{ toJSON(github) }}"
      
      - name: Checkout
        run: |
          echo "checkout"
