name: Lede-CI
on: workflow_dispatch

jobs:
  build:
    name: ""
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        run: |
          echo "${{ toJSON(github) }}"
      
      - name: Checkout
        run: |
          echo "checkout"
