name: "Build CI for Lede firmware"
run-name: "Building Lede firmware #${{ github.run_number }} (${{ github.run_attempt }})"

on: workflow_dispatch

jobs:
  build:
    name: Building Lede firmware
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lede
    steps:
      - name: Setup
        run: |
          # Create work directory
          mkdir ./lede
          
          # Setup timezone
          sudo -E timedatectl set-timezone "Asia/Shanghai"
          
          # Upgrade
          sudo -E apt update -y
          sudo -E apt full-upgrade -y
          
          # Install dependencies
          sudo -E apt install -y git ack antlr3 aria2 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev
          
          # Cleanup
          sudo -E apt autoremove --purge
          sudo -E apt clean
      
      - name: Checkout
        run: |
          # Checkout
          git clone https://github.com/coolsnowwolf/lede.git .
          
      - name: Update feeds
        run: |
          # Add software source
          echo "src-git kenzo https://github.com/kenzok8/openwrt-packages" >> ./feeds.conf.default
          echo "src-git small https://github.com/kenzok8/small" >> ./feeds.conf.default
          
          # Update and install
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Generate config
        run: |
          # Custom config
          # Include
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_DEVICE_generic=y
          CONFIG_PACKAGE_6in4=y
          CONFIG_PACKAGE_frpc=y
          CONFIG_PACKAGE_glib2=y
          CONFIG_PACKAGE_ip6tables=y
          CONFIG_PACKAGE_ipv6helper=y
          CONFIG_PACKAGE_kmod-fuse=y
          CONFIG_PACKAGE_kmod-ip6tables=y
          CONFIG_PACKAGE_kmod-ipt-nat6=y
          CONFIG_PACKAGE_kmod-iptunnel=y
          CONFIG_PACKAGE_kmod-nf-ipt6=y
          CONFIG_PACKAGE_kmod-nf-log6=y
          CONFIG_PACKAGE_kmod-nf-nat6=y
          CONFIG_PACKAGE_kmod-nf-reject6=y
          CONFIG_PACKAGE_kmod-sit=y
          CONFIG_PACKAGE_libdnet=y
          CONFIG_PACKAGE_libffi=y
          CONFIG_PACKAGE_libfuse3=y
          CONFIG_PACKAGE_libmspack=y
          CONFIG_PACKAGE_libpcre2=y
          CONFIG_PACKAGE_luci-app-frpc=y
          CONFIG_PACKAGE_luci-i18n-frpc-zh-cn=y
          CONFIG_PACKAGE_luci-lib-json=y
          CONFIG_PACKAGE_luci-mod-rpc=y
          CONFIG_PACKAGE_luci-proto-ipv6=y
          CONFIG_PACKAGE_odhcp6c=y
          CONFIG_PACKAGE_odhcp6c_ext_cer_id=0
          CONFIG_PACKAGE_odhcpd-ipv6only=y
          CONFIG_PACKAGE_odhcpd_ipv6only_ext_cer_id=0
          CONFIG_PACKAGE_open-vm-tools=y
          CONFIG_PACKAGE_open-vm-tools-fuse=y
          CONFIG_PCRE2_JIT_ENABLED=y
          CONFIG_TARGET_KERNEL_PARTSIZE=128
          CONFIG_TARGET_ROOTFS_PARTSIZE=512
          EOF
          
          # Exclude
          echo "# CONFIG_PACKAGE_UnblockNeteaseMusic-Go is not set" >> .config
          echo "# CONFIG_PACKAGE_adbyby is not set" >> .config
          echo "# CONFIG_PACKAGE_attr is not set" >> .config
          echo "# CONFIG_PACKAGE_automount is not set" >> .config
          echo "# CONFIG_PACKAGE_autosamba is not set" >> .config
          echo "# CONFIG_PACKAGE_avahi-dbus-daemon is not set" >> .config
          echo "# CONFIG_PACKAGE_blkid is not set" >> .config
          echo "# CONFIG_PACKAGE_dbus is not set" >> .config
          echo "# CONFIG_PACKAGE_etherwake is not set" >> .config
          echo "# CONFIG_PACKAGE_iptables-mod-ipsec is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-crypto-cbc is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-crypto-deflate is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-crypto-des is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-crypto-echainiv is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-crypto-hmac is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-crypto-kpp is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-crypto-md5 is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-fs-exfat is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-fs-ext4 is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-fs-ntfs3 is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-ipsec is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-ipt-ipsec is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-iptunnel6 is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-lib-crc16 is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-nf-conntrack-netlink is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-scsi-core is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-usb-storage is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-usb-storage-extras is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-usb-storage-uas is not set" >> .config
          echo "# CONFIG_PACKAGE_kmod-wireguard is not set" >> .config
          echo "# CONFIG_PACKAGE_libavahi-client is not set" >> .config
          echo "# CONFIG_PACKAGE_libavahi-dbus-support is not set" >> .config
          echo "# CONFIG_PACKAGE_libcap is not set" >> .config
          echo "# CONFIG_PACKAGE_libdaemon is not set" >> .config
          echo "# CONFIG_PACKAGE_libdbus is not set" >> .config
          echo "# CONFIG_PACKAGE_libexpat is not set" >> .config
          echo "# CONFIG_PACKAGE_libgmp is not set" >> .config
          echo "# CONFIG_PACKAGE_libgnutls is not set" >> .config
          echo "# CONFIG_PACKAGE_libminiupnpc is not set" >> .config
          echo "# CONFIG_PACKAGE_libnatpmp is not set" >> .config
          echo "# CONFIG_PACKAGE_libnettle is not set" >> .config
          echo "# CONFIG_PACKAGE_libparted is not set" >> .config
          echo "# CONFIG_PACKAGE_libpopt is not set" >> .config
          echo "# CONFIG_PACKAGE_libstdcpp is not set" >> .config
          echo "# CONFIG_PACKAGE_libtasn1 is not set" >> .config
          echo "# CONFIG_PACKAGE_liburing is not set" >> .config
          echo "# CONFIG_PACKAGE_libuv is not set" >> .config
          echo "# CONFIG_PACKAGE_libwebsockets-full is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-accesscontrol is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-adbyby-plus is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-autoreboot is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-ddns is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-diskman is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-nlbwmon is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-samba4 is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-ttyd is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-unblockmusic is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-unblockmusic_INCLUDE_UnblockNeteaseMusic_Go is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-vsftpd is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-wireguard is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-wol is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-xlnetacc is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-app-zerotier is not set" >> .config
          echo "# CONFIG_PACKAGE_luci-proto-wireguard is not set" >> .config
          echo "# CONFIG_PACKAGE_nlbwmon is not set" >> .config
          echo "# CONFIG_PACKAGE_parted is not set" >> .config
          echo "# CONFIG_PACKAGE_samba4-libs is not set" >> .config
          echo "# CONFIG_PACKAGE_samba4-server is not set" >> .config
          echo "# CONFIG_PACKAGE_smartmontools is not set" >> .config
          echo "# CONFIG_PACKAGE_strongswan is not set" >> .config
          echo "# CONFIG_PACKAGE_ttyd is not set" >> .config
          echo "# CONFIG_PACKAGE_vsftpd-alt is not set" >> .config
          echo "# CONFIG_PACKAGE_wireguard-tools is not set" >> .config
          echo "# CONFIG_PACKAGE_wol is not set" >> .config
          echo "# CONFIG_PACKAGE_wsdd2 is not set" >> .config
          echo "# CONFIG_PACKAGE_zerotier is not set" >> .config       
          
          # Merge
          make defconfig
          
      - name: Download package
        run: |
          make download -j16
        
      - name: Compile firmware
        run: |
          make -j$(nproc) || make -j1 V=s
          
      - name: Prepare artifact
        run: |
          # Generate version
          echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
          
          # Packaging
          mkdir -p ./artifact/{package,buildinfo}
          rm -rf $(find ./bin/targets/ -type d -name "packages")
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
          
      - name: Upload buildinfo
        uses: actions/upload-artifact@v3
        with:
          name: "lede-${{ env.VERSION }}-buildinfo"
          path: ./artifact/buildinfo/

      - name: Upload package
        uses: actions/upload-artifact@v3
        with:
          name: "lede-${{ env.VERSION }}-package"
          path: ./artifact/package/

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: "lede-${{ env.VERSION }}-firmware"
          path: ./bin/targets/
